### ISSUE TITLE
YouTube links don't work anymore

### ISSUE THREAD

**Issue by NomarCub** [zolrath/obsidian-auto-link-title#8] opened 2021-04-28 08:11 UTC
They used to be fine, but now YouTube channel or video links don't yield a real title but `Before you continue to YouTube`.

![](https://user-images.githubusercontent.com/5298006/116369149-56d67780-a809-11eb-843b-a4dec2e08359.gif)

Links used: `https://www.youtube.com/teded`, `https://www.youtube.com/watch?v=xy9nj94xvKA`.

It looks like YouTube's cookie consent page's title for when you first open the site in a browser.

![image](https://user-images.githubusercontent.com/5298006/116369351-92714180-a809-11eb-8967-32881a56b6ef.png)

**Comment by zolrath** [comment] 2021-04-28 19:34
Hmm interesting, those are both still resolving correctly for me
```
[TED-Ed - YouTube](https://www.youtube.com/teded)
[How do wind turbines work? - Rebecca J. Barthelmie and Sara C. Pryor - YouTube](https://www.youtube.com/watch?v=xy9nj94xvKA)
```
I see that if I can block cookies from `consent.youtube.com` this screen can be bypassed but there doesn't seem to be any method of disabling cookies in the electron WebBrowser.

I can block all web requests to that url in my electron WebBrowser but I'm not certain if that will have the intended effect as I can't seem to recreate that behavior myself.

**Comment by NomarCub** [comment] 2021-04-28 20:14
I've also tried [this plugin](https://github.com/stefan-vatov/auto-link-title-obsidian), which still works for me for YouTube.

**Comment by zolrath** [comment] 2021-04-28 21:32
I had no idea that plugin existed! Interesting, if I had found that when I started I likely would have just done some pull requests instead. Seems it utilizes `node-fetch`, I'll check to see if node-fetch passes the muster on sites that the CORS proxy failed on and do some comparisons as I want to ensure this plugin supports mobile.

**Comment by zolrath** [comment] 2021-04-28 22:02
Hm yeah, that solution fails on domains that enforce CORS so if you attempted to paste:
https://www.newegg.com/
or
https://www.reddit.com/r/ObsidianMD/
it fails to resolve the title.

I'll continue to see if I can reproduce the consent.youtube.com cookie issue, I'll ping you on discord to see if my filter blocking web requests to that subdomain corrects the issue for you.

**Comment by Akimaru666** [comment] 2021-06-25 09:54
Any news ? I also face this issue

**Comment by NomarCub** [comment] 2021-07-19 21:57
The new Obsidian release ([v0.12.11](https://forum.obsidian.md/t/obsidian-release-v0-12-11-insider-build/21184)) might help with CORS restrictions.

**Comment by NomarCub** [comment] 2022-01-22 12:32
YouTube videos work now (a change on YouTube's end), but channels and playlists still turn up as `Before you continue to YouTube`.

@zolrath do you think this is possible now, with the [Obsidian CORS API update](https://forum.obsidian.md/t/obsidian-release-v0-12-11-insider-build/21184) and stuff that is in the [other plugin](https://github.com/stefan-vatov/auto-link-title-obsidian)?

**Comment by aidan-gibson** [comment] 2022-05-21 21:26
YouTube Videos, channels, and playlists work for me.

**Comment by scruel** [comment] 2022-10-27 09:30
For china users, we need proxy settings to let it work, will it be possible to be added in the plugin or only can have it in Obsidian itself?

**Comment by NomarCub** [comment] 2022-10-27 09:32
Now videos often turn up "Site Unreachable" but find the right title with the refresh command.

**Comment by nj9106** [comment] 2023-12-19 05:45
> For china users, we need proxy settings to let it work, will it be possible to be added in the plugin or only can have it in Obsidian itself?

![image](https://github.com/zolrath/obsidian-auto-link-title/assets/1883735/ca864a93-44ac-463c-8400-88efe4c1d818)
add below line in main.js of the plugin.
window.webContents.session.setProxy({"mode":"system"});

**Closed** 2024-01-04 08:33 UTC
